spring:
#  redis:
#    # Redis服务器地址
#    host: 127.0.0.1
#    # Redis服务器连接端口
#    port: 6379
#    # Redis服务器连接密码（默认为空）
#    password: 123456
#    # 连接超时时间（毫秒）
#    timeout: 0
#    pool:
#      # 连接池最大连接数（使用负值表示没有限制）
#      max-active: 8
#      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-wait: -1
#      # 连接池中的最大空闲连接
#      max-idle: 8
#      # 连接池中的最小空闲连接
#      min-idle: 0
  thymeleaf:
    # 关闭thymeleaf缓存 开发时使用 否则没有实时画面
    cache: false
    # 让html标签书写校验不会那么严格
    mode: LEGACYHTML5
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    # 重点：autoReconnect=true 当数据库连接异常中断时，是否自动重新连接，要配置这个utf8mb4才能正确读取
    # 需要注意的是，在xml配置文件中，url中的&符号需要转义成  &amp;
    # allowMultiQueries=true 开启批量执行sql
    url: jdbc:mysql://localhost:3306/binghe_demo?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: Abc123D
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: binghe
#    password: binghe
#    virtual-host: /binghemq
mybatis:
  # 实体类所在的包路径
  type-aliases-package: com.binghe.demo.pojo
  # mybatis配置文件路径
  config-location: classpath:mybatis/mybatis-config.xml
  # mybatis的映射的xml文件路径
  mapper-locations: classpath:mybatis/mapper/*.xml